# Site settings
title: Teddy Marty
description: Mon curriculum vitae
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Teddy Marty
user_description_title: Pour résumer
user_description: Développeur depuis 2012, je me suis spécialisé dans les technologies DotNet de Microsoft. J'ai suivi l'enseignement de "l'apprentissage par problème" délivrée par l'Exia Cesi, et je suis actuellement employé par l'ESN GFI dans laquelle j'occupe le poste d'Ingénieur Etude et Développement DotNet.</br> Je vous invite à visiter mon profile LinkedIn pour d'information.
user_title: Ingénieur étude et développement
# email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum


# Google-analytics
google-analytics:
  id: "UA-156099340-1"

exclude: ['package.json', 'src' , 'node_modules']
